version: 1
services:
  - type: web
    name: lifevault
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /